### ISSUE TITLE
Method missing generate_attr_taxable_methods (activerecord 2.3) in taxable_test.rb

### ISSUE THREAD

**Issue by CloCkWeRX** [ept/invoicing#6]
Running the tests produces:
/usr/share/ruby-rvm/gems/ruby-1.9.3-p194@invoicing/gems/activerecord-2.3.14/lib/active_record/base.rb:1998:in `method_missing': undefined method`generate_attr_taxable_methods' for #Class:0x9c8bed8 (NoMethodError)
    from /home/clockwerx/invoicing/invoicing/lib/invoicing/taxable.rb:225:in `block in acts_as_taxable'
    from /home/clockwerx/invoicing/invoicing/lib/invoicing/taxable.rb:225:in`each'
    from /home/clockwerx/invoicing/invoicing/lib/invoicing/taxable.rb:225:in `acts_as_taxable'
    from /home/clockwerx/invoicing/invoicing/test/taxable_test.rb:53:in`class:TaxableRecord'
    from /home/clockwerx/invoicing/invoicing/test/taxable_test.rb:50:in `<class:TaxableTest>'
    from /home/clockwerx/invoicing/invoicing/test/taxable_test.rb:5:in`<top (required)>'

... and I can't figure out why exactly - for some reason the ClassMethods aren't being included?

**Comment by iffyuva** [comment]
No support for Rails 2.x :|
